import { useState, useEffect } from 'react';
import { Card } from '../ui/Card';
import { motion } from 'framer-motion';

export function DrawCountdown({ nextDrawDate }) {
  const [timeLeft, setTimeLeft] = useState({ days: 0, hours: 0, minutes: 0, seconds: 0 });

  useEffect(() => {
    if (!nextDrawDate) return;

    const target = new Date(nextDrawDate).getTime();

    const interval = setInterval(() => {
      const now = new Date().getTime();
      const difference = target - now;

      if (difference <= 0) {
        clearInterval(interval);
        setTimeLeft({ days: 0, hours: 0, minutes: 0, seconds: 0 });
      } else {
        setTimeLeft({
          days: Math.floor(difference / (1000 * 60 * 60 * 24)),
          hours: Math.floor((difference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)),
          minutes: Math.floor((difference % (1000 * 60 * 60)) / (1000 * 60)),
          seconds: Math.floor((difference % (1000 * 60)) / 1000)
        });
      }
    }, 1000);

    return () => clearInterval(interval);
  }, [nextDrawDate]);

  const TimeUnit = ({ value, label }) => (
    <div className="flex flex-col items-center">
      <div className="w-16 h-16 md:w-20 md:h-20 glass rounded-2xl flex items-center justify-center border border-accent/20 shadow-inner">
        <span className="text-2xl md:text-3xl font-heading font-black text-white">
          {value.toString().padStart(2, '0')}
        </span>
      </div>
      <span className="text-xs text-muted uppercase tracking-widest font-bold mt-3">{label}</span>
    </div>
  );

  return (
    <Card glow="cyan" className="relative overflow-hidden text-center p-8 md:p-12">
      <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-transparent via-accent to-transparent" />
      
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <h3 className="font-heading font-bold text-xl md:text-2xl text-white mb-2">Next Algorithmic Draw</h3>
        <p className="text-muted mb-8">Generated by verifiably random cryptographics</p>
        
        <div className="flex items-center justify-center gap-4 md:gap-6">
          <TimeUnit value={timeLeft.days} label="Days" />
          <span className="text-2xl font-bold text-muted/50 mb-8">:</span>
          <TimeUnit value={timeLeft.hours} label="Hours" />
          <span className="text-2xl font-bold text-muted/50 mb-8">:</span>
          <TimeUnit value={timeLeft.minutes} label="Mins" />
          <span className="text-2xl font-bold text-muted/50 hidden sm:block mb-8">:</span>
          <div className="hidden sm:block">
            <TimeUnit value={timeLeft.seconds} label="Secs" />
          </div>
        </div>
      </motion.div>
    </Card>
  );
}
